### ISSUE TITLE
Links to http://www.makelinux.net/reference broken

### ISSUE THREAD

**Issue by flo2k** [makelinux/linux_kernel_map#3]
Hi,

Again, me.

I just recognised that the links to http://www.makelinux.net/reference don't work correctly. It seems that some open, but then are redirected to other pages, which are not found anymore.

I tested the links of:
- Device Model
- Virtual memory
- Virtual file system

Are you able to update the Linux kernel map with working links, or is this not possible because the link targets are problematic?

Best,

flo2k

**Comment by bittner** [comment]
Looks like all those references are now updated with appropriate external links, correct?

**Comment by flo2k** [comment]
@bittner thanks a lot for fixing this. I still like the kernel map a lot.
