### ISSUE TITLE
Map won't show on Firefox

### ISSUE THREAD

**Issue by CohenAriel** [makelinux/linux_kernel_map#4]

**Comment by makelinux** [comment]
Thank you!
Which release of Firefox? Which URL? Any errors?

**Comment by CohenAriel** [comment]
I'm sorry, I didn't have time to make a proper bug report.
It seems to work now. I'm using Windows, Firefox 99.0.1 (64-bit).
This was the URL - https://makelinux.github.io/kernel/map/
I then tried on Edge and it worked, and now it works in Firefox too, though I don't know what changed, I didn't empty the cache or anything.

**Comment by makelinux** [comment]
Sometimes there are temporal issues in Internet.
Thank you.
